import type { Metadata } from "next";
import { Montserrat, Nunito, Raleway } from "next/font/google";
import "./globals.css";
import Footer from "@/components/Footer";

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
});

const nunito = Nunito({
  variable: "--font-nunito",
  subsets: ["latin"],
});

const raleway = Raleway({
  variable: "--font-raleway",
  subsets: ["latin"],
});

// Next.js converts this into <title> and <meta> tags in the <head> section,
// which you don't see on the page but search engines and browser tabs do
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${montserrat.variable} ${nunito.variable} ${raleway.variable} antialiased`}>
        {children} {/* this is where each page's content gets inserted (like your home page, blog page, events page, etc.) */}
        <Footer />
      </body>
    </html>
  );
}
